channels:
  - conda-forge
dependencies:
  - timm=0.9.12
  - transformers=4.32.1
  - pycocotools>=2.0.6
  - torchmetrics=1.2.1
  - tensorboard=2.15.1
  - buildingregulariser>=0.2.2
  - geopandas=1.1.1
  - pip
  - pip:
    - torch==2.1.2
    - torchvision==0.16.2
    - torchaudio==2.1.2
    - albumentations==1.3.1
    - imageio==2.33.1
    - matplotlib-inline==0.1.6
    - opencv-python-headless==4.8.1.78
    - scikit-image==0.22.0
    - scikit-learn==1.3.2
    - scipy==1.11.4
    - shapely==2.0.4
    - fastapi>=0.68.0
    - uvicorn>=0.15.0
    - python-multipart>=0.0.5
    - tqdm>=4.62.0
    - diskcache>=5.6.0
    - huggingface-hub>=0.15.1,<1.0
  
